### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by ReenigneArcher** [lmangani/polyfill-glibc-action#1]
I'm trying to use this to make some github actions work on a very old ubuntu 16.04 container.

I used the following:

```yaml
      - name: Get current glibc version
        id: glibc
        if: matrix.UPGRADE_GLIBC == true
        run: |
          echo "GLIBC_VERSION=$(ldd --version | head -n 1 | awk '{print $NF}')" >> $GITHUB_OUTPUT

      - name: Patch glibc for backwards compatibility
        id: polyfill
        if: matrix.UPGRADE_GLIBC == true
        uses: lmangani/polyfill-glibc-action@1.1.4
        with:
          glibc: "${{ steps.glibc.outputs.GLIBC_VERSION }}"
          target: "/__e/node20/bin/node"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
```

But get the same error as before:

```
> Run actions/checkout@v4
  with:
    submodules: recursive
    repository: ReenigneArcher/moonlight-qt
    token: ***
    ssh-strict: true
    ssh-user: git
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    show-progress: true
    lfs: false
    set-safe-directory: true
/usr/bin/docker exec  b6c747e10137a8e47515a9089cfec3a6cdfa535b163355b454d3c16b691784e8 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```

I added a debug step to print the output of the action, but the result is blank.

```yaml
      - name: Debug binary
        if: matrix.UPGRADE_GLIBC == true
        run: |
          echo "${{ steps.polyfill.outputs.binary }}"
```

result:

```
> Run echo ""
  echo ""
  shell: bash --noprofile --norc -e -o pipefail {0}
```

Am I doing something incorrectly? From my understanding polyfill needs to run on the "new system", which I believe this action is doing since it's using docker.

**Comment by lmangani** [comment]
Hello @ReenigneArcher you don't need to use the current glibc in settings but rather the target glibc you want to polyfill. 
Here's a working example from one of my pipelines to polyfill for glibc 2.27 backwards compatibility in a go application.

```
 - name: Patch glibc for backwards compatibility
      uses: lmangani/polyfill-glibc-action@1.1.4
      continue-on-error: true
      id: polyfill
      with:
        glibc: "2.27"
        target: "/github/workspace/your_binary"
```
